# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dom', models.CharField(max_length=30)),
                ('css_selector', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=300)),
                ('content_identifiers', models.ManyToManyField(to='crawl.ContentIdentifier')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('link', models.CharField(max_length=300)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl.Input')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='posts',
            field=models.ManyToManyField(to='crawl.Post'),
        ),
    ]
