# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0003_auto_20161127_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentidentifier',
            name='css_selector',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
