# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0005_auto_20161127_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
